version: '3'

services:
    server:
        build: ./
        environment:
            - REDIS_HOST=redis
        ports:
            - "5000:5000"
        depends_on:
            - redis
    redis:
        image: redis:5.0-alpine
